# Generated by Django 5.2 on 2025-05-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='tipo',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
